-- ============================================================
-- HMS  Supabase setup
-- Run this once in the Supabase Dashboard -> SQL Editor
-- (Create new query, paste, Run)
--
-- Tables:
--   hms_store    -> mirrors the old Firebase RTDB root node. One
--                   row per localStorage key ("users", "todos", ...).
--                   payload holds the full array/object blob.
--   hms_live_pops-> mirror of the old "live_pops" push-notification
--                   node used by the dashboard popup system.
--
-- Realtime: postgres_changes requires tables in the
--           "supabase_realtime" publication. We add them below.
-- ============================================================

-- ---------- main data store ----------
-- note: the app reads/writes this table via supabase-js as
-- { key, data } (see js/sync.js: hms_store.upsert({key, data})),
-- so the payload column is named "data", not "payload".
create table if not exists public.hms_store (
  key        text primary key,
  data       jsonb not null,
  updated_at timestamptz not null default now()
);

-- ---------- live pop notifications ----------
create table if not exists public.hms_live_pops (
  id         bigint generated by default as identity primary key,
  payload    jsonb not null,
  created_at timestamptz not null default now()
);

-- ---------- row-level security ----------
-- The static app only holds a publishable/anon key, so RLS must
-- allow the "anon" role to read and write (same trust model as the
-- old Firebase RTDB which was fully open).
alter table public.hms_store     enable row level security;
alter table public.hms_live_pops enable row level security;

drop policy if exists "hms_store_anon_access"     on public.hms_store;
drop policy if exists "hms_live_pops_anon_access" on public.hms_live_pops;
drop policy if exists "hms_store_auth_access"     on public.hms_store;
drop policy if exists "hms_live_pops_auth_access" on public.hms_live_pops;

create policy "hms_store_anon_access"
  on public.hms_store
  for all
  to anon
  using (true)
  with check (true);

create policy "hms_live_pops_anon_access"
  on public.hms_live_pops
  for all
  to anon
  using (true)
  with check (true);

-- Also allow the "authenticated" role (in case service keys are
-- ever used later).
create policy "hms_store_auth_access"
  on public.hms_store
  for all
  to authenticated
  using (true)
  with check (true);

create policy "hms_live_pops_auth_access"
  on public.hms_live_pops
  for all
  to authenticated
  using (true)
  with check (true);

-- ---------- push notification subscriptions ----------
-- One row per browser/desktop/mobile push subscription. The app
-- registers each device here (client uses ws-notifications.js); the
-- Supabase Database Webhook on hms_live_pops INSERT calls the
-- push-relay Edge Function, which reads this table and sends
-- Web Push / FCM so notifications arrive even when the app is
-- closed (background/phone/desktop).
create table if not exists public.hms_push_subs (
  id         uuid primary key default gen_random_uuid(),
  user_id    text not null,
  platform   text not null default 'web',   -- web | android | desktop
  endpoint   text,
  p256dh     text,
  auth       text,
  fcm_token  text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint hms_push_subs_endpoint_key unique (endpoint),
  constraint hms_push_subs_fcm_key     unique (fcm_token)
);

alter table public.hms_push_subs enable row level security;

drop policy if exists "hms_push_subs_anon_access" on public.hms_push_subs;
drop policy if exists "hms_push_subs_auth_access" on public.hms_push_subs;

create policy "hms_push_subs_anon_access"
  on public.hms_push_subs
  for all
  to anon
  using (true)
  with check (true);

create policy "hms_push_subs_auth_access"
  on public.hms_push_subs
  for all
  to authenticated
  using (true)
  with check (true);

-- ---------- realtime publication ----------
alter table public.hms_store     replica identity full;
alter table public.hms_live_pops replica identity full;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'hms_store'
  ) then
    alter publication supabase_realtime add table public.hms_store;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'hms_live_pops'
  ) then
    alter publication supabase_realtime add table public.hms_live_pops;
  end if;
end $$;
